name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: setup-maven-settings
        uses: s4u/maven-settings-action@v1
        with:
         servers: '[{"id": "github", "username": "skirankumars31@gmail.com", "password": "ec231dc157e0231baafabab7d3d8506fbdb911ff"}]'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Deploy with Maven
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn deploy --file pom.xml
